src/API/Data/AuthorizationRepository.cs
src/API/Data/BuildingRelationshipsRepository.cs
src/API/Data/UnitsRepository.cs
src/API/Functions/BuildingRelationships.cs
src/API/Functions/Buildings.cs
src/API/Functions/Units.cs
src/API/Middleware/Request.cs
src/Models/DTO/BuildingRelationshipResponse.cs
src/Models/DTO/SupportRelationshipResponse.cs
src/Models/Entities/Unit.cs
tests/API/Integration/BuildingRelationshipsTests.cs
tests/API/Integration/UnitsTests.cs

Implement remaining Unit endpoints:
* "get unit children"
* "get unit members"
* "get buildings supported by unit"
* "get departments supported by unit"
* "get tools accessible by unit"
And from Jared's punchlist: 
* On "get unit members" ensure member notes are stripped as appropriate 
* On "delete unit" ensure no Unit relations are orphaned

Implementing remaing Unit endpoints

---

src/Tasks/host.json

Durable function apps can throw out of memory exceptions if there's a lot of data being passed from an orchestrator to an activity. This is one recommended way to address that. See also this [GitHub issue](https://github.com/Azure/azure-functions-durable-extension/issues/340).

Address OutOfMemory exception on durable tasks

---

src/API/Middleware/Security.cs

When determining whether a JWT was expired (`exp`) or not net valid (`nbf`) we would convert the current UNIX time to a DateTime. This conversion sometimes erroneously resulted in a DateTime that was set a few minutes in the future. The JWT validation check would fail because the JWT appeared as not yet valid.
This PR simplifies the method of comparing the JWT `nbf` and `exp` and fixes the bug.
Fixes #20

Fix comparisons of system and JWT nbf/exp times

---

src/API/Data/DataRepository.cs
src/API/Functions/Authorization.cs
src/API/Functions/Healthcheck.cs
src/API/Middleware/Logging.cs
src/API/Middleware/Pipeline.cs
src/API/Middleware/Response.cs
src/Tasks/Logging.cs
src/Tasks/People.cs

* Create Serilog ILogger instances only as needed. 
* Don't log API GET requests; log everything else.
* Make all logging async. 
* Use consistent JSON serialization settings when logging object bodies.
Resolves #25

Reduce API/Tasks memory consumption

---

pipelines/azure-pipelines-template.yml
src/Database/Migrations/20210329154226_UpdateHrPeopleWithMarkedForDeleteFlag.Designer.cs
src/Database/Migrations/20210329154226_UpdateHrPeopleWithMarkedForDeleteFlag.cs
src/Models/Entities/HrPerson.cs
src/Tasks/Buildings.cs
src/Tasks/DTO.cs
src/Tasks/Logging.cs
src/Tasks/People.cs
src/Tasks/Tools.cs
src/Tasks/Utils.cs

* Reduce memory footprint by not passing Profile data between activity functions. This reduces memory overhead of the function app and eliminates storage ingress/egress of people data blobs.
* Rework HR People and Building tasks to batch upsert DB records. This reduces DB chattiness, CPU consumption, and App Insights logging.
* Implement singleton pattern for durable orchestrators, to ensure only one instance of a given task orchestration is running at any one time.
* Add unit/integration tests back to the DevOps pipeline.

Minimize task resource footprint.

---

src/API/Middleware/Security.cs
tests/API/Integration/AuthenticationTests.cs

The API was returning HTTP 400 in case of a missing or non-bearer JWT. By sending an HTTP 401, the frontend will know to send the user to IU Login for authentication. (This was the behavior of the V1 API.)

Fix unexpected blank screen / errors when browsing to deep link

---

src/Models/Lsp/LspContact.cs
src/Models/TestEntities/TestEntities.cs
tests/API/Integration/LspTests.cs

Resolves #43
If the LSP's unit has an email that is the preferred email, otherwise default to their personal email.
* Updates existing test to reflect this change.
* Adds a test that verifies the two cases(unit with no email, and a unit with an email)

LspContact.PreferredEmail from Unit

---

pipelines/azure-pipelines-template.yml

Azure DevOps stages are [executed serially unless you specify otherwise](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#specify-dependencies). This PR enables the Test and Package stages to be run concurrently.

DevOps: Remove implicit dependency Package has on Test stage

---

src/API/Data/PeopleRepository.cs
src/API/Data/UnitMembersRepository.cs
src/Models/DTO/PeopleLookupItem.cs
src/Models/DTO/UnitMemberRequest.cs
tests/API/Integration/UnitMembersTests.cs

Resolving Issues #47 and #48
The react app depends on NetId being capitalized correctly while our app frequently uses Netid. We have decided to leave the rest of the renaming alone until we rewrite the client. 
Additionally, we had issues with creating a new object with null strings instead of empty strings. The client doesn't particularly null strings either.

Create unit member bug

---

src/API/Data/PeopleRepository.cs
src/Models/TestEntities/TestEntities.cs
tests/API/Integration/PeopleTests.cs

When searching for people based on
`{LastName}, {FirstName}`
split it into a tuple of 
`(firstName, lastName)`
so that the query can do a wildcard search using our standard name format
`{First Name}%{LastName}%`

Improve people search

---

src/Web/Pages/PersonProfile.razor
src/Web/Shared/ModalForm.razor
src/Web/Shared/ProfileExpertise.razor
src/Web/Shared/ProfileResponsibilities.razor
src/Web/wwwroot/index.html
src/Web/wwwroot/js/interop.js

Adds components with two-way binding on the Person parameter for modifying `Person.Expertise` and `Person.Responsibilities`.
Adds a parameter, `ConfirmBeforeClose`, to `ModalForm` that lets us use JS Interop to prevent closing a modal when the form has been changed.
When fetching suggestions for Expertise from Stack Exchange it makes a cancellable request to reduce extra calls while the user is still typing.

Make Expertise and Responsibilities Modals Their Own Components

---

src/Web/Pages/People.razor

Handle deep linking to filtered results, just browsing to `/people`, or looking at filtered results and browsing back to `/people`.
The heart of this change is using a `NavigationManager.LocationChanged()` event to kick off parsing the query parameters and submitting our request to the API.

People Location Changes

---

src/API/Data/SupportRelationshipsRepository.cs
src/API/Functions/SupportRelationships.cs
src/Models/DTO/SsspSupportRelationshipResponse.cs
src/Models/Entities/SupportRelationship.cs
tests/API/Integration/SupportRelationshipsTests.cs

Adds a `/SsspSupportRelationships` endpoint to the API.
This generates a list of all the SupportRelationshp with email information, gotten either by the `Unit.Email` value or by getting the emails for the Leaders of a unit that does not have an email set.
Corey Tarbell has been generating this data with a query that can be simplified to
```pgsql
SELECT DISTINCT d.name AS dept, d.description AS dept_desc,
CASE
WHEN u.email IS NULL THEN p.campus_email
WHEN TRIM(u.email) = '' THEN p.campus_email
ELSE u.email
END AS contact_email
FROM support_relationships sr
INNER JOIN departments d ON d.id = sr.department_id
INNER JOIN units u
ON u.id = sr.unit_id
AND u.active
LEFT OUTER JOIN unit_members um
ON um.unit_id = u.id
AND um.role = 4 --Leaders only
LEFT OUTER JOIN people p ON p.id = um.person_id …
```

SSSP Endpoint

---

src/API/Data/AuthorizationRepository.cs
src/API/Functions/Units.cs
src/Web/Pages/Units/Unit.razor
tests/API/Integration/UnitsTests.cs

For the test unit he is in the role of owner, he can still see the icons to archive and delete the unit even though he doesn’t have permission. Are those icons only supposed to appear for superadmins?
As Owner:
As Member:
As Service Admin:

Unit archive delete permissions

---

src/API/Data/DepartmentsRepository.cs
src/API/Functions/Departments.cs
src/API/Functions/PeopleSearchParameters.cs
src/Web/Pages/Search.razor
tests/API/Integration/DepartmentsTests.cs

`DepartmentsRepository.GetAll()` had a hard-coded limit of returning 25 results.
This changes the behavior to default to returning all results, but adding a `_limit` query parameter to constrain the number of results returned.
I've updated all the requests in the web app to use `_limit` where it used to expect to always get a max of 25 records. (Interestingly the department suggestions when establishing a SupportRelationship for a unit was already trying to use `_limit`, but now it actually works 😜

Department GetAll limit

---

src/API/Data/AuthorizationRepository.cs
src/API/Functions/Units.cs
tests/API/Integration/UnitMemberToolsTests.cs
tests/API/Integration/UnitsTests.cs

Corey presented an issue where Jolene was in a parent unit as an Owner, but she was unable to edit a child unit's members. This adds tests and resolves the issue on the assumption that Owners, ManageMembers, and ManageTools are all inherited from the parent units (recursively).

Inherit permissions

---

src/API/API.csproj
src/API/Data/PeopleRepository.cs
src/API/Data/UnitMembersRepository.cs
src/API/Functions/People.cs
src/API/local.settings.json.example
src/Models/DTO/PeopleLookupItem.cs

This is specifically to deal with Academic Non-Appointed folks like Andrea Ricci(`anricci`) who never show up in the IMS API, but are real users.
Actually querying LDAP to find them by username was trivial, see `PeopleRepositor.TryFindPersonWithAd()`.
Massaging this into existing pipelines that only expected to find results from the `People` table and `HrPeople` table was rough.  Which is why this commit grew to be so big.

Use Active Directory to Find Users Not in HrPeople Table

---

pipelines/azure-pipelines-template.yml

This morning we ran out of space on the `/home` mount on build agent `escssdba01`, and `escssdba02` was down to 66 MB free.
The cause was that all the nuget packages, for all of our projects, were getting stored in the `/home/cssd/.nuget` folder, which does not jive with ELA's preferred drive sizes.
The solution is to cache the NuGet packages at `/opt/cssd/nuget` where we have lost of space.  This would be trivial to do if we were super-users on these machines by setting the ENV `NUGET_PACKAGES` to `/opt/cssd/nuget`; but we aren't super-users, and pestering the ELA admins to do it for us is a hassle.
The solution is to let individual pipelines set `NUGET_PACKAGES` for just that run.

Build Agent NuGet Cache

---

src/Web/wwwroot/appsettings.Staging.json
src/Web/wwwroot/appsettings.json

Updating the staging web app to use the same new UAA clientId for OAuth authentication that have been configured in the staging API.

Staging Frontend UAA Client Setting

---

Dockerfile.State
pact/StateServer/StateServer.csproj
tests/API/Integration/UnitsTests.cs

A bug was introduced in PR #94 where it would fail to build the docker image for the `Dockerfile.State`, and would instead reuse a previously created image with the expected tag.
The container is used to reset the state of the database between tests, and went unnoticed until the changes were merged into PR #92 and tests started failing because the cached image wasn't truncating all the tables.
This is only an issue when running tests or attempting to deploy the project using the DevOps pipelines, so it will not need its own release, but can be merged into `develop` and be part of the next desired production release.

State State Server Fix

---

tests/API/Integration/Scaffolding/PostgresContainer.cs

This PR is a formality.  The change ensures that our database client works with the version of Postgres our test and production databases will be upgraded to in the near future.

Tests Use Postgres 14.7

---

src/API/Middleware/Response.cs
src/API/Middleware/Security.cs

[STRY0013096 - Add Logging For Successful Lsp Functions GET Requests](https://servicenow.iu.edu/nav_to.do?uri=rm_story.do?sys_id=cb40d2291b22ad5016c02fc4bd4bcb2d%26sysparm_view=scrum)
This PR updates the IT People logging logic so that successful GET requests against the legacy LSP functions are logged. It also removes the custom logging logic from the `Security.ValidateIpAddress` method. 
Normally, successful GET requests are not logged, but we want to log successful GET requests against the LSP functions, as these functions are now IP restricted and we may be asked to audit their usage. After this change, successful GET requests to the LSP functions will be logged. Failed GET requests were already logged.
Finally, I've removed the custom logging code from the …

STRY0013096 Add Logging For Successful Lsp Functions GET Requests

---

pipelines/azure-pipelines-template.yml

[STRY0012376](https://iu.service-now.com/nav_to.do?uri=rm_story.do?sys_id=4a197d7c4790d9909286dfbd436d4315%26sysparm_view=scrum) - Cleanup Steps for Docker Tasks on Linux Build Agents
On our Linux build agents we sometimes run out f space on the device where our Docker data is stored.  These changes ensure that we are disposing of unused images, volumes, and cached build artifacts.
I have used the new commands locally and on one of the build agents, but running this pipeline for the test environment will be the most meaningful test.

Build Agent Housekeeping

---

src/API/Functions/BuildingRelationships.cs
src/API/Functions/Buildings.cs
src/API/Functions/Departments.cs
src/API/Functions/People.cs
src/API/Functions/SupportRelationships.cs
src/API/Functions/UnitMemberTools.cs
src/API/Functions/UnitMembers.cs
src/API/Functions/Units.cs
src/API/Middleware/Utils.cs
tests/API/Integration/BuildingRelationshipsTests.cs
tests/API/Integration/BuildingsTests.cs
tests/API/Integration/DepartmentsTests.cs
tests/API/Integration/PeopleTests.cs
tests/API/Integration/SupportRelationshipsTests.cs
tests/API/Integration/UnitMemberToolsTests.cs
tests/API/Integration/UnitMembersTests.cs
tests/API/Integration/UnitsTests.cs

[STRY0013055 - Bug - Bug - API returns 500 Errors When Passed a String](https://servicenow.iu.edu/nav_to.do?uri=rm_story.do?sys_id=c3da00a91b86e91416c02fc4bd4bcbb7%26sysparm_view=scrum)
This PR fixes an issue where passing a string to a function endpoint that requires an integer would cause the endpoint return a 500 error instead of a 400 error. Our initial endpoint definitions required an int parameter, but did not verify that the value passed into the endpoint was a valid integer value. The result was a 500 error.
This PR updates our endpoint functions to explicitly attempt to convert `id` parameters to integer values before passing them into our internal functions. If the value cannot be converted into an integer, the server will return a 400 (Bad Request) error.
In terms of …

STRY0013055 Api Returns 500 Errors When Passed a String

---

tests/API/Integration/Scaffolding/PostgresContainer.cs

[STRY0013490 - Update Postgres Container to use new version (14.8.0) image](https://servicenow.iu.edu/nav_to.do?uri=rm_story.do?sys_id=54eda97e477b2d909286dfbd436d437d%26sysparm_view=scrum)
Quick PR to update the integration tests container to test against the 14.8.0 Postgres database image. This is in preparation for the upcoming database server update to Postgres 14.8.0.

STRY0013490: Update Postgres Container to use new version (14.8.0) image

---

tests/API/Integration/Scaffolding/PostgresContainer.cs

**Do Not Merge Before August 30**
The Postgres DBAs will be updating the test and production database servers Sunday, August 27 2023, between 00:00 and 01:00 AM to address [CVE-2023-39417](https://www.postgresql.org/support/security/CVE-2023-39417/).
This PR updates the Postgres Docker image used for tests to 14.9 to ensure IT People will keep working after this weekend's emergency patching.

INC1339853 - Postgres Quarterly Patching

---

src/Tasks/People.cs
tests/API/Integration/Scaffolding/PostgresContainer.cs

[INC1394692](https://servicenow.iu.edu/nav_to.do?uri=incident.do?sys_id=b7ea52e74795b1d0e06785e8536d438e) - UpdateDepartmentRecords Task Failing
Today we received alerts about the `UpdateDepartmentRecords` task failing on test.  Some fresh data from the IMS Profile API resulted in an entry in the `hr_people` table that had a valid `hr_department`, but `hr_department_desc` was null.  Which caused `UpdateDepartmentRecords` to fail because `departments.description` cannot be null.
This PR adds null checks that will prevent a scenario where it tries to INSERT or UPDATE a department record with a null `description`.

Updating Departments Null Checks

---

src/Web/Pages/People.razor

[STRY0013738](https://servicenow.iu.edu/nav_to.do?uri=rm_story.do?sys_id=1f05abce4706f510e06785e8536d4393%26sysparm_view=scrum) -  Bug - People Export CSV Button Not Working
The "Export results to CSV" button on the `/people` page was failing because it was using an incorrect encoding.  I cribbed the correct values from the UCMP project.  Now the button works.
Tested locally and in test environment.

People Export CSV Button Not Working

---

src/Web/Pages/Privacy.razor
src/Web/wwwroot/swagger-ui/cssd.css

[STRY0013717](https://iu.service-now.com/nav_to.do?uri=rm_story.do?sys_id=c22dc83347a1bd909286dfbd436d435f%26sysparm_view=scrum) - API Documentation Accessibility Issues
This is a follow-up to #109.  A subsequent scan pointed out two more styles that have contrast that is too low.
This PR will deploy to the test environment, where we can confirm the updated styles are working correctly.
The version has become high-contrast gray
The `<code>` elements now looks like an old orange monochrome monitor.

Style to enhance contrast for the version-stamp and pre/code elements.

---

pact/StateServer/StateServer.csproj
pipelines/azure-pipelines-template.yml
src/API/API.csproj
src/API/Functions/Healthcheck.cs
src/API/Middleware/Logging.cs
src/API/Middleware/Request.cs
src/API/Middleware/Response.cs
src/Database/Database.csproj
src/Tasks/Tasks.csproj
tests/API/Integration/Integration.csproj
tests/API/Integration/LoggingTests.cs
tests/API/Integration/Scaffolding/DockerContainer.cs

This is a redo of PR #114 which had issues with ping timeouts we could not track down.  It is revised to ditch the various package updates and other changes - and simply does the minimum to get Serilogger writing to Postgres correctly again.
A bug in the logging services was discovered while attempting to address [INC1831717](https://servicenow.iu.edu/nav_to.do?uri=incident.do?sys_id=a646645e476e0ad0e06785e8536d431b).
When IT People was pulled-up to .Net 8 in #113  our PostgreSQL SeriLog sink started failing silently for most POST and PUT requests.  This was because the `LogProps.RequestBody` `ColumnWriter` uses the `NpgsqlDbType.Json`, which blows up when it receives a value that is not `null` or well-formed JSON.  With the upgrade to .Net 8 `LogProps.RequestBody` would often be provided …

Logging issues Redo
